### ISSUE TITLE
【suggestion】To your mod propertymodifier

### ISSUE THREAD

**Issue by blood789** [IchHabeHunger54/Biomaticraft#1]
some advices
1、In the form of a folder, rather than a single json file to edit the item. Because all items are placed in a json file, it will look messy.

2、Use classified JSON files to edit different items, and the content is displayed in vertical instead of horizontal.  For example, if I modify the hardness of dozens or even hundreds of squares, the horizontal display will be very long. And it is difficult to modify later. If you use the vertical display, it will look very clear. 
LIKE THIS:
hardness：
{
Minecraft：stone；10
Minecraft：dirt；10
....
....
}

instead of
｛Minecraft：stone；10；Minecraft：dirt；10；.................｝

You can refer to the file of crafttweaker .

**Comment by blood789** [comment]
Looking forward to the 1.18.1 update

**Comment by IchHabeHunger54** [comment]
1. This is not the Property Modifier issue tracker, please use that one instead.
2. Property Modifier never had JSONs (apart from the two item tags)
3. Property Modifier in this pack is not on the newest 1.16.5 version either; a lot has changed since then.
4. I dislike the idea of moving to JSON.
5. A folder would be useless, too.
